-- ==============================================================
-- Flyway migration: V1__create_food_item.sql
-- --------------------------------------------------------------
-- This script creates the first table that maps to the
-- com.edson.model.FoodItem entity.
--
-- It is executed automatically by Flyway when your application starts,
-- provided that Flyway is enabled in `application.properties`.
-- ==============================================================

CREATE TABLE IF NOT EXISTS food_item (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,      -- PK – generated by the DB
    name            VARCHAR(255) NOT NULL,                  -- column for @Column(nullable = false)
    category        VARCHAR(50)  NOT NULL,                  -- ENUM is stored as a string
    quantity        INTEGER,                                -- nullable (default)
    expiration_date TIMESTAMP                              -- LocalDateTime -> TIMESTAMP in H2
);
